// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TupleLab.ApiDb;

#nullable disable

namespace TupleLab.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260214215000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("TupleLab.ApiDb.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Apple",
                            Price = 5.2m
                        },
                        new
                        {
                            Id = 2,
                            IsActive = false,
                            Name = "PS5",
                            Price = 650m
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Toothpick",
                            Price = 1.5m
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Lemon Tarts",
                            Price = 5.2m
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Cheese",
                            Price = 8.75m
                        },
                        new
                        {
                            Id = 6,
                            IsActive = false,
                            Name = "Flour",
                            Price = 23.18m
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "Corn Syrup",
                            Price = 5.36m
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Name = "Ginsing",
                            Price = 45.8m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
